name: Cron Example

on:
  # schedule:
  #   - cron: "* * * * *"
  workflow_dispatch:


jobs:
  run-integration-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: cron-example

    steps:
      - uses: actions/checkout@v2

      # Setup Nodejs
      - name: Setup Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      # Install yarn
      - name: Install Yarn
        run: yarn install --global yarn

      # Install libraries
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Run tests
      - name: Run tests
        run: yarn test